kind = "mobile"
previewPath = "/weflix-mobile/"
title = "WeFlix"
version = "1.0.0"
id = "artifacts/weflix-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/weflix-mobile/" ]
localPort = 18448

[services.development]
run = "pnpm --filter @workspace/weflix-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/weflix-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/weflix-mobile", "run", "serve" ]

[services.env]
PORT = "18448"
BASE_PATH = "/weflix-mobile/"
